name: pummel_the_fish
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"
  flutter: "3.10.4"

dependencies:
  cloud_firestore: ^4.8.0
  collection: ^1.17.1

  firebase_core: ^2.13.1
  flutter:
    sdk: flutter
  http: ^1.0.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
          weight: 400
        - asset: assets/fonts/Comfortaa-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700
    - family: Titillium Web
      fonts:
        - asset: assets/fonts/TitilliumWeb-Bold.ttf
          weight: 700
        - asset: assets/fonts/TitilliumWeb-Black.ttf
          weight: 900
  assets:
    # Eine einzelne Datei hinzufügen:
    - assets/images/logo.png
    - assets/images/pummel.png
    - assets/images/dog.jpg
    - assets/images/cat.jpg
    - assets/images/bird.jpg
    - assets/images/fish.jpg
    # Oder den ganzen images Ordner hinzufügen:
    # - assets/images/
