name: pummel_the_fish
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"
  flutter: "3.10.4"

dependencies:
  collection: ^1.17.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    # Eine einzelne Datei hinzufügen:
    - assets/images/logo.png
    - assets/images/pummel.png
    - assets/images/dog.jpg
    - assets/images/cat.jpg
    - assets/images/bird.jpg
    - assets/images/fish.jpg
    # Oder den ganzen images Ordner hinzufügen:
    # - assets/images/
